[book]
authors = ["Matthias Vogelgesang"]
language = "en"
multilingual = false
src = "."
title = "axum notes"

[output.html]
git-repository-url = "https://github.com/matze/axum-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/matze/axum-notes/edit/master/{path}"
