[package]
name = "templating-with-askama"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0", features = ["with-axum"] }
askama_axum = { version = "0" }
axum = "0.4"
tokio = { version = "1", features = ["full"] }
